# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 17:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 6, 15, 17, 18, 34, 70503, tzinfo=utc), max_length=900),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(),
        ),
    ]
