# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_auto_20160615_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=90),
        ),
    ]
