# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_auto_20160615_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='description',
        ),
    ]
