# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_announcement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
