# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0007_announcement_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='published_date',
        ),
    ]
