# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0010_auto_20160616_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='published_date',
            field=models.CharField(default=b'2016-06-16 13:54:14', max_length=75),
        ),
    ]
