# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0011_auto_20160616_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
